version: '2' 
services:
  config-service:
    container_name: config-service
    hostname: config-service
    image: config-service
    networks:
      - default
    ports:
      - "9090:9090"

  user-service:
    container_name: user-service
    hostname: user-service
    image: user-service
    networks:
      - default
    ports:
      - "2144:2144"

networks:
  default:
    driver: bridge
