version: '2' 
services:
  post-service:
    container_name: post-service
    image: post-service
    networks:
      - default
    ports:
      - "2142:2142"

  document-service:
    container_name: document-service
    image: document-service
    networks:
      - default
    ports:
      - "2143:2143"

  user-service:
    container_name: user-service
    image: user-service
    networks:
      - default
    ports:
      - "2144:2144"

networks:
  default:
    external:
      name: default1