version: '2' 
services:
  config-service:
    container_name: config-service
    hostname: config-service
    image: config-service
    networks:
      - default
    ports:
      - "9090:9090"

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - config-service
    command: config-service:9090

  eureka-service:
    container_name: eureka-service
    image: eureka-service
    networks:
      - default
    ports:
      - "9091:9091"
    depends_on:
      - start_dependencies

  post-service:
    container_name: post-service
    hostname: post-service
    image: post-service
    networks:
      - default
    ports:
      - "2142:2142"
    depends_on:
      - start_dependencies

  document-service:
    container_name: document-service
    hostname: document-service
    image: document-service
    networks:
      - default
    ports:
      - "2143:2143"
    depends_on:
      - start_dependencies

  user-service:
    container_name: user-service
    hostname: user-service
    image: user-service
    networks:
      - default
    ports:
      - "2144:2144"
    depends_on:
      - start_dependencies

networks:
  default:
    driver: bridge
